spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
